export type RiskFactors = {
  id: string;
  studentId: string;
  assessmentDate: string;
  academicRiskLevel: string;
  behavioralRiskLevel: string;
  attendanceRiskLevel: string;
  socialEmotionalRiskLevel: string;
  dropoutRisk?: number;
  academicFactors?: string;
  behavioralFactors?: string;
  attendanceFactors?: string;
  socialFactors?: string;
  familyFactors?: string;
  protectiveFactors?: string;
  interventionsNeeded?: string;
  alertsGenerated?: string;
  followUpActions?: string;
  assignedCounselor?: string;
  parentNotified: boolean;
  parentNotificationDate?: string;
  overallRiskScore?: number;
  status: string;
  nextAssessmentDate?: string;
  notes?: string;
};
